### ISSUE TITLE
Reinstalling Magisk app randomly makes app lose root - cached app uid is out of update?

### ISSUE THREAD

**Issue by canyie** [canyie/Magisk#8]
Device: vince
Android version: 12
Magisk version name: 78a444d6
Magisk version code: 25206

Uninstalled then installed the app, it showed "Installed N/A" and lost root.
```
E/SuRequestHandler$init: java.io.FileNotFoundException: /dev/socket/77cbBMdHc3O9d1RD6G4PsAOHb: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:575)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
        at com.topjohnwu.magisk.core.su.SuRequestHandler$init$2.invokeSuspend(SuRequestHandler.kt:63)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7728)
        at libcore.io.IoBridge.open(IoBridge.java:561)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:125) 
        at com.topjohnwu.magisk.core.su.SuRequestHandler$init$2.invokeSuspend(SuRequestHandler.kt:63) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
After reinstalling the app, its uid is 10196, but magisk still sets the owner of the fifo to 10195
![image](https://user-images.githubusercontent.com/31466456/210129341-509aa5ea-b345-4f88-8950-093c0bca258f.png)
![image](https://user-images.githubusercontent.com/31466456/210129346-3bfce75b-938a-423b-a6e3-ae68989fa39a.png)

After I uninstalled another app (which triggered cache
![image](https://user-images.githubusercontent.com/31466456/210129481-d37e17ab-4e61-4561-929d-6c62b3503a8a.png)
 refreshing?), the app begins to work again

**Comment by canyie** [comment]
Maybe fixed by a1ce6f5f120b1ce61d567cbd1f89d66cd5cf36a2
